/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alquileres.visual;

import alquileres.Registro;
import alquileres.RegistroDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class NewRegistro extends javax.swing.JFrame {

    /**
     * Creates new form NewRegistro
     */
    public NewRegistro() {
        initComponents();
       // Para que aparezca en medio de la pantalla
       setLocationRelativeTo(null);
       // Quitamos las pestañas 2 y 3 para que tengan que rellenar los datos para avanzar
       Panel_registro.setEnabledAt(1, false);
       Panel_registro.setEnabledAt(2, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_registro = new javax.swing.JTabbedPane();
        pAlquiler = new javax.swing.JPanel();
        bSiguienteAlquiler = new javax.swing.JButton();
        bCancelar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        lMeses = new javax.swing.JLabel();
        tFId = new javax.swing.JTextField();
        dFecha = new javax.swing.JSpinner();
        dMeses = new jbean.bean.NumericTextField();
        pCliente = new javax.swing.JPanel();
        bSiguienteCliente = new javax.swing.JButton();
        bAtrasCliente = new javax.swing.JButton();
        bCancelar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tApellidos = new javax.swing.JTextField();
        tDni = new javax.swing.JTextField();
        nTelefono = new jbean.bean.NumericTextField();
        tCorreo = new javax.swing.JTextField();
        pPropiedad = new javax.swing.JPanel();
        bRegistrar = new javax.swing.JButton();
        bAtrasPropiedad = new javax.swing.JButton();
        bCancelar3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tVivienda = new javax.swing.JTextField();
        tUbicacion = new javax.swing.JTextField();
        nMetros = new jbean.bean.NumericTextField();
        nHabitaciones = new jbean.bean.NumericTextField();
        nMensualidad = new jbean.bean.NumericTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSiguienteAlquiler.setText("Siguiente");
        bSiguienteAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteAlquilerActionPerformed(evt);
            }
        });

        bCancelar1.setText("Cancelar");
        bCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelar1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alquiler"));

        lId.setText("ID");

        lFecha.setText("Fecha de entrada");

        lMeses.setText("Meses de contrato");

        dFecha.setModel(new javax.swing.SpinnerDateModel());

        dMeses.setText("numericTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lFecha)
                    .addComponent(lId)
                    .addComponent(lMeses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tFId)
                    .addComponent(dFecha)
                    .addComponent(dMeses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(tFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFecha)
                    .addComponent(dFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMeses)
                    .addComponent(dMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pAlquilerLayout = new javax.swing.GroupLayout(pAlquiler);
        pAlquiler.setLayout(pAlquilerLayout);
        pAlquilerLayout.setHorizontalGroup(
            pAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlquilerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCancelar1)
                        .addGap(18, 18, 18)
                        .addComponent(bSiguienteAlquiler))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pAlquilerLayout.setVerticalGroup(
            pAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSiguienteAlquiler)
                    .addComponent(bCancelar1))
                .addContainerGap())
        );

        Panel_registro.addTab("Alquiler", pAlquiler);

        bSiguienteCliente.setText("Siguiente");
        bSiguienteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteClienteActionPerformed(evt);
            }
        });

        bAtrasCliente.setText("Atras");
        bAtrasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasClienteActionPerformed(evt);
            }
        });

        bCancelar2.setText("Cancelar");
        bCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelar2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cliente"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        jLabel4.setText("NºTelefono");

        jLabel5.setText("Correo");

        nTelefono.setText("numericTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(tApellidos)
                        .addComponent(tDni)
                        .addComponent(nTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pClienteLayout = new javax.swing.GroupLayout(pCliente);
        pCliente.setLayout(pClienteLayout);
        pClienteLayout.setHorizontalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClienteLayout.createSequentialGroup()
                        .addGap(0, 184, Short.MAX_VALUE)
                        .addComponent(bCancelar2)
                        .addGap(18, 18, 18)
                        .addComponent(bAtrasCliente)
                        .addGap(18, 18, 18)
                        .addComponent(bSiguienteCliente))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pClienteLayout.setVerticalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSiguienteCliente)
                    .addComponent(bAtrasCliente)
                    .addComponent(bCancelar2))
                .addContainerGap())
        );

        Panel_registro.addTab("Cliente", pCliente);

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        bAtrasPropiedad.setText("Atras");
        bAtrasPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasPropiedadActionPerformed(evt);
            }
        });

        bCancelar3.setText("Cancelar");
        bCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelar3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la propiedad"));

        jLabel6.setText("ID vivienda");

        jLabel7.setText("Ubicacion");

        jLabel8.setText("Metros");

        jLabel9.setText("Numero de habitaciones");

        jLabel10.setText("Mensualidad");

        nMetros.setText("numericTextField1");

        nHabitaciones.setText("numericTextField2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nMensualidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(nHabitaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nMetros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pPropiedadLayout = new javax.swing.GroupLayout(pPropiedad);
        pPropiedad.setLayout(pPropiedadLayout);
        pPropiedadLayout.setHorizontalGroup(
            pPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPropiedadLayout.createSequentialGroup()
                        .addGap(0, 187, Short.MAX_VALUE)
                        .addComponent(bCancelar3)
                        .addGap(18, 18, 18)
                        .addComponent(bAtrasPropiedad)
                        .addGap(18, 18, 18)
                        .addComponent(bRegistrar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pPropiedadLayout.setVerticalGroup(
            pPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrar)
                    .addComponent(bAtrasPropiedad)
                    .addComponent(bCancelar3))
                .addContainerGap())
        );

        Panel_registro.addTab("Propiedad", pPropiedad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_registro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_registro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //va a la pestña cliente
    private void bSiguienteAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteAlquilerActionPerformed
       if(tFId.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Rellene todos los campos antes de continuar por favor");
       }else{
        Panel_registro.setSelectedIndex(1);
        Panel_registro.setEnabledAt(1, true);
        Panel_registro.setEnabledAt(0, false);
       }
    }//GEN-LAST:event_bSiguienteAlquilerActionPerformed
    //va a la pestaña propiedad
    private void bSiguienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteClienteActionPerformed
        if(tNombre.getText().isEmpty()||tApellidos.getText().isEmpty()||nTelefono.getText().isEmpty()||tDni.getText().isEmpty()||tCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellene todos los campos antes de continuar por favor");
        }else{
        Panel_registro.setSelectedIndex(2);
        Panel_registro.setEnabledAt(2, true);
        Panel_registro.setEnabledAt(1, false);
        }   
    }//GEN-LAST:event_bSiguienteClienteActionPerformed
    //va a la pestaña alquiler
    private void bAtrasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasClienteActionPerformed
        Panel_registro.setSelectedIndex(0);
        Panel_registro.setEnabledAt(0, true);
        Panel_registro.setEnabledAt(1, false);
    }//GEN-LAST:event_bAtrasClienteActionPerformed

    private void bCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelar1ActionPerformed
        Main nuevoFrame= new Main();
        nuevoFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nuevoFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bCancelar1ActionPerformed

    private void bCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelar2ActionPerformed
        Main nuevoFrame= new Main();
        nuevoFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nuevoFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bCancelar2ActionPerformed

    private void bCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelar3ActionPerformed
        Main nuevoFrame= new Main();
        nuevoFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nuevoFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bCancelar3ActionPerformed
    //va a la pestaña cliente
    private void bAtrasPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasPropiedadActionPerformed
        Panel_registro.setSelectedIndex(1);
        Panel_registro.setEnabledAt(1, true);
        Panel_registro.setEnabledAt(2, false);
    }//GEN-LAST:event_bAtrasPropiedadActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        if(tVivienda.getText().isEmpty()||tUbicacion.getText().isEmpty()||nHabitaciones.getText().isEmpty()||nMensualidad.getText().isEmpty()||nMetros.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellene todos los campos antes de continuar por favor");
        }else{
          //creamos un date y la formateamos para hacerla un string y asi ahorrarnos problemas a la hora de almacenarla ya que las fechas son muy puñeteras
          //para ser almacenadas .
          Date fechaEntrada=(Date) dFecha.getValue();
          SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy-MM-dd");
          
          //instanciamos un objeto de la clase registro y guardamos todos los contenidos del formulario en el.
          Registro registro= new Registro();
          registro.setNombre(tNombre.getText());
          registro.setApellidos(tApellidos.getText());
          registro.setDni(tDni.getText());
          registro.setId(tFId.getText());
          registro.setCorreo(tCorreo.getText());
          registro.setIdPropiedad(tVivienda.getText());
          registro.setUbicacion(tUbicacion.getText());
          registro.setDiaEntrada(formatoFecha.format(fechaEntrada));
          registro.setMesesContrato(dMeses.getText());
          registro.setnTelefono(nTelefono.getValueAsInt());
          registro.setMetros(nMetros.getValueAsInt());
          registro.setnHabitaciones(nHabitaciones.getValueAsInt());
          registro.setMensualidad(nMensualidad.getValueAsInt());
          JOptionPane.showMessageDialog(null, "Registro guardado con exito");
          RegistroDAO.guardarRegistro(registro);
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panel_registro;
    private javax.swing.JButton bAtrasCliente;
    private javax.swing.JButton bAtrasPropiedad;
    private javax.swing.JButton bCancelar1;
    private javax.swing.JButton bCancelar2;
    private javax.swing.JButton bCancelar3;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JButton bSiguienteAlquiler;
    private javax.swing.JButton bSiguienteCliente;
    private javax.swing.JSpinner dFecha;
    private jbean.bean.NumericTextField dMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lMeses;
    private jbean.bean.NumericTextField nHabitaciones;
    private jbean.bean.NumericTextField nMensualidad;
    private jbean.bean.NumericTextField nMetros;
    private jbean.bean.NumericTextField nTelefono;
    private javax.swing.JPanel pAlquiler;
    private javax.swing.JPanel pCliente;
    private javax.swing.JPanel pPropiedad;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tDni;
    private javax.swing.JTextField tFId;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tUbicacion;
    private javax.swing.JTextField tVivienda;
    // End of variables declaration//GEN-END:variables
}
